### PR TITLE
try to fix Ti error

### LINKED ISSUE #336: key :Ti not found
```julia
using EarthDataLab
using DimensionalData
using Zarr, YAXArrays, NetCDF, DiskArrays

# other relevant packages
# using Statistics, Dates, SkipNan

ra = esdc(res="tiny")

ra_tair = ra[variable=At("air_temperature_2m")]
ra_resp = ra[variable=At("terrestrial_ecosystem_respiration")]
ds = Dataset(tair=ra_tair, resp=ra_resp)
f = "./DATA/hello.zarr"
savedataset(ds, path=f, driver=:zarr, overwrite=true)
```

```julia
ERROR: KeyError: key :Ti not found
Stacktrace:
 [1] getindex(h::Dict{Symbol, Int64}, key::Symbol)
   @ Base .\dict.jl:484
 [2] #93
   @ .\none:0 [inlined]
 [3] iterate
   @ .\generator.jl:47 [inlined]
 [4] collect(itr::Base.Generator{Base.KeySet{Symbol, Dict{Symbol, DimensionalData.Dimensions.Dimension}}, YAXArrays.Datasets.var"#93#99"{Dict{Symbol, Int64}}})
   @ Base .\array.jl:782
 [5] savedataset(ds::Dataset; path::String, persist::Nothing, overwrite::Bool, append::Bool, skeleton::Bool, backend::Symbol, driver::Symbol, max_cache::Float64, writefac::Float64, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ YAXArrays.Datasets C:\Users\kongdd\.julia\packages\YAXArrays\lvvMa\src\DatasetAPI\Datasets.jl:562
```

### PR DESCRIPTION
**Pull request by kongdd**
try to fix #336, #330, #320, might also works for #301 

This issue is related to `DD.dim2key(ti)` and `DD.name(ti)`. They return different values.

```julia
using DimensionalData
using DimensionalData: DimensionalData as DD
using Dates

ti = Ti(DateTime(2001):Month(1):DateTime(2002))

@show DD.dim2key(ti);
@show DD.name(ti);
```
```
DD.dim2key(ti) = :Ti
DD.name(ti) = :Time
```

### CODE REVIEW

**Comment by lazarusA** [comment]
Thanks for this PR, could you please try to include a test example. For now, I approved CI to check if nothing breaks as it is.

**Comment by kongdd** [comment]
Thank you. After all tests passed, I will add new.

**Comment by kongdd** [comment]
@lazarusA, do you know about the `Broken` in tests?

It shows that 9 broken. But I can't found out which test failed.

image

<https://github.com/JuliaDataCubes/YAXArrays.jl/actions/runs/6368945266/job/17288790299?pr=337>

**Comment by kongdd** [comment]
The test of `Datasets` is commented. I am not sure whether should I uncomment this line.
<https://github.com/JuliaDataCubes/YAXArrays.jl/blob/4f4f555cb1583dff91e437bbd684a7de471ed498/test/runtests.jl#L15>

**Comment by kongdd** [comment]
https://github.com/JuliaDataCubes/YAXArrays.jl/issues/336, https://github.com/JuliaDataCubes/YAXArrays.jl/issues/330 are solved now. https://github.com/JuliaDataCubes/YAXArrays.jl/issues/320 should also be. But I have no data to test.

**Comment by lazarusA** [comment]
I'm doing another CI run. Let's see, I cannot do much today, only things from my phone. I could take a deeper look once I'm at my computer

**Comment by kongdd** [comment]
Thank you @lazarusA. 
An ugly test was added here. All tests in `datasets.jl` are uncommented and passsed now.
image

**Comment by lazarusA** [comment]
Could you use https://juliadatacubes.github.io/YAXArrays.jl/dev/examples/generated/UserGuide/openNetCDF/ ? It's Ti still appearing when reading the files?

**Comment by kongdd** [comment]
Sure. New test Added and Passed.
image

**Comment by kongdd** [comment]
I found both of `DD.dim2key` and `DD.name` are used in `YAXArrays.jl`. Their different return values might lead to bugs unexpectedly.

**Pull request merged**
