### PR TITLE
Fixing link in docs

### PR DESCRIPTION
**Pull request by MartinuzziFrancesco**

### CODE REVIEW

**Comment by lazarusA** [comment]
thanks... a lot of things changed in the last two weeks. I will need to finish this one first https://github.com/JuliaDataCubes/YAXArrays.jl/tree/up_workflow (which is suppose to be now a more stable release for DocumenterVitepress).  So that the docs work properly again.

**Comment by MartinuzziFrancesco** [comment]
The new docs are really good! I didn't know about the work in the other branch so we can close this one. I just thought it was a quick fix

**Comment by lazarusA** [comment]
yes, after merging that one, things should be easier, and hopefully quick fixes :D

**Comment by MartinuzziFrancesco** [comment]
I'll be on the lookout then!

**Pull request closed without merging**
